<?php

namespace App\Faker;

use Faker\Provider\Base;

class CategoriaProvider extends Base
{
    private const CATEGORIAS = [
        'Alimentos e bebidas à base de plantas',
        'Alimentos à base de plantas',
        'Lanches comida',
        'Lanches doces',
        'Bebidas',
        'Cereais e Batatas',
        'Biscoitos e Bolos',
        'Laticínios',
        'Biscoitos',
        'Cereais e seus produtos',
        'Bebidas à base de plantas',
        'Alimentos Congelados',
        'Alimentos Fermentados',
        'Produtos lácteos fermentados',
        'Produtos para barrar',
        'Produtos sem glútem',
        'Pequenos alomoços',
        'Refeições',
        'Petiscos salgados',
        'Alimentos à base de frutas e legumes',
        'Molhos',
        'Confeitaria',
        'Pães',
        'Sucos e néctares',
        'Bebidas à base de frutas',
        'Doces para barrar',
        'Chocolates',
        'Queijos',
        'Bebidas carbonatadas',
        'Sementes',
        'Gorduras',
        'Sodas',
        'Produtos secos',
        'Produtos para barrar à base de plantas',
        'Legumes e seus produtos',
        'Leites',
        'Produtos à base de carne',
        'Carnes',
        'Massa alimentícia',
        'Bebidas quentes',
        'Refeições com carne',
        'Alimentos à base de vegetais',
        'Legumes',
        'Chás',
        'Grãos de cereais',
        'Aperitivos',
        'Alimentos à base de frutas',
        'Produtos secos a serem rehidratados',
        'Doces',
        'Conservas de fruta',
        'Bebidas alcoólicas',
        'Iogurtes',
        'Bombons de chocolate',
        'Nozes e seus produtos',
        'Bebidas adoçadas',
        'Comida enlatada',
        'Barras',
        'Bolachas',
        'Adoçantes',
        'Águas',
        'Condimentos',
        'Gorduras para barrar',
        'Sobremesas',
        'Biscoitos recheados',
        'Néctares de frutas',
        'Gorduras vegetals',
        'Cereias para pequeno-almoçco',
        'Refeições com frango',
        'Pães especiais',
        'Farinha',
        'Biscoitos de chocolate',
        'Águas de nascente',
        'Molhos de tomate',
        'Manteigas',
        'Gorduras lácteas',
        'Gorduras animais',
        'Água Mineral',
        'Bebidas não alcoólicas',
        'Nozes',
        'Ketchup',
        'Chocolates de leite',
        'Cervejas',
        'Macarrão Instantâneo',
        'Olios vegetais',
        'Arrozes',
        'Maioneses',
        'Farinhas de cereais',
        'Carnes preparadas',
        'Pratos de massa',
        'Sobremesas congeladas',
        'Amendoins',
        'Alimentos à base de plantas enlatados',
        'Frutas',
        'refrigerante',
        'Gelados e sorvetes',
        'Barras de chocolate',
        'Sanduiches',
        'Cafés',
        'Saquinhos de chá',
        'Produtos de oliveira',
        'Açucar',
        'Vegetais enlatados',
        'Pós de chocolate',
        'Batatas fritas',
        'Azeite de oliva',
        'Azeites virgem extra',
        'Farinhas de trigo',
        'Temperos',
        'Chocolates amargos',
        'Frutos do mar',
        'Sopas',
        'Rebuçados e gomas',
        'Chás com sabor',
        'Iogurtes gregos',
        'Refeições desidratadas',
        'Bebidas artificialmente doçeadas',
        'Vinhos',
        'Massas secas',
        'Produtos agrícolas',
        'Peixe',
        'pacoca',
        'Sumos de fruta',
        'Néctares de uva',
        'Chás de ervas',
        'Bebidas fermentadas',
        'Bebidas lácteas fermentadas',
        'Brioche',
        'Leites UHT',
        'Suplemento alimentar',
        'Pães de forma',
        'Pulsos',
        'Sopa Instantânea',
        'Panettone',
        'Colas',
        'Atum',
        'Sementes de legumes',
        'Alimentos à base de plantas secos',
        'Peixe enlatado',
        'Méis',
        'creme-de-leite',
        'Produtos des abelhas',
        'Leites desnatados',
        'nuggets',
        'pao-de-queijo',
        'Bombons',
        'Avícolas',
        'Produtos salgados para barrar',
        'salgadinho',
        'Frutas secas',
        'Iogurtes de fruta',
        'pacoca-rolha',
        'puffed-corn-snacks',
        'Coco',
        'Alimentos frescos',
        'Barras de cereais',
        'Galinha',
        'Aditivo alimentar',
        'Leites integrais',
        'Bolos',
        'Pizzas',
        'leite-de-coco',
        'Sobremesas de chocolate',
        'achocolatado-em-po',
        'Queijos de vaca',
        'bebidas-nao-alcolicas',
        'Bebidas não adoçadas',
        'leite-em-po',
        'pao-integral',
        'Picles',
        'bala',
        'Gelado',
        'Néctares de manga',
        'atuns-em-filete',
        'Farelo de aveia',
        'salame',
        'biscoito-salgado',
        'Tostas',
        'Tortilhas de batata',
        'leite-condensado',
        'Mostardas',
        'Doces de pêssego',
        'Ovos',
        'Pizzas congeladas',
        'Vinhos tintos',
        'biscoito-integral',
        'chocolate-amargo',
        'Legumes congelados',
        'salgadinho-de-milho'
    ];

    public function categoria(): string
    {
        return self::randomElement(self::CATEGORIAS);
    }
}
